feat: transform catalog in coroutine
Informasjonsforvaltning/fdk-data-transformation-service pull request #5
Opened 2021-03-17 12:25 UTC by NilsOveTen

2021-03-17 15:28 UTC, azaxarov requested changes

2021-03-17 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/rdf/BR.kt
> +        val orgPath: Property = m.createProperty(uri + "orgPath")
```suggestion
        val uri = "https://raw.githubusercontent.com/Informasjonsforvaltning/organization-catalogue/master/src/main/resources/ontology/organization-catalogue.owl#"

        val orgPath: Property = ResourceFactory.createProperty(uri + "orgPath")
```

2021-03-17 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/rdf/RDFUtils.kt
> +        responseModel.read(StringReader(responseBody), BACKUP_BASE_URI, rdfLanguage.name)
Tror at dette skal også være mulig:
```suggestion
    try {
        ModelFactory.createDefaultModel().read(responseBody, BACKUP_BASE_URI, rdfLanguage.name)
```

2021-03-17 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/RDFAdapter.kt
> +class RDFAdapter {
Trenger ikke denne klassen i det hele tatt. Se på `RDFDataMgr.loadModel()`

2021-03-17 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/SPARQLAdapter.kt
> +class SPARQLAdapter {
RDFConnectionFuseki bør være en enklere alternativ

2021-03-17 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/env/Env.kt
> +        ?: System.getProperty("uris.sparqlservice", "http://localhost:3030")
Det bør gå an å skrive alt som en funksjon og/eller enum

2021-03-18 05:53 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/env/Env.kt
> +        ?: System.getProperty("uris.sparqlservice", "http://localhost:3030")
Eeh, noe i denne duren?
4c439e3

2021-03-18 05:58 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/SPARQLAdapter.kt
> +class SPARQLAdapter {
Ja, kanskje det. Men har lite lyst til å rote meg inn i RDFConnectionFuseki igjen. Sist vi brukte den så feilet det veldig hardt på store modeller, brukte noen GB med minne ved hver lagring. Og nå opererer vi med mye større modeller...

2021-03-18 07:34 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/rdf/BR.kt
> +        val orgPath: Property = m.createProperty(uri + "orgPath")
bb497a1

2021-03-18 07:34 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/RDFAdapter.kt
> +class RDFAdapter {
Nice, TIL

bb497a1

2021-03-18 07:35 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/rdf/RDFUtils.kt
> +        responseModel.read(StringReader(responseBody), BACKUP_BASE_URI, rdfLanguage.name)
Hadde ikke behov for denne når jeg fjernet RDFAdapter: bb497a1

2021-03-18 10:32 UTC, azaxarov approved these changes

2021-03-18 10:33 UTC, azaxarov approved these changes

2021-03-19 09:12 UTC, merged