spring boot application & rabbitmq trigger
Informasjonsforvaltning/fdk-data-transformation-service pull request #6
Opened 2021-03-19 14:48 UTC by NilsOveTen

2021-03-19 15:28 UTC, azaxarov requested changes

2021-03-19 15:28 UTC, azaxarov commented on Dockerfile
> +COPY /target/fdk-data-transformation-service.jar app.jar
Navnet på output jar bør styres i pom.xml slik at alle dockerfiler ser likt ut
```
<build>
    ...
    <finalName>app</finalName>
    ...
</build>
```

2021-03-19 15:28 UTC, azaxarov commented on pom.xml
> +        <finalName>${project.artifactId}</finalName>
```suggestion
        <finalName>app</finalName>
```

2021-03-19 15:28 UTC, azaxarov commented on pom.xml
> +        <version>2.4.2</version>
2.4.4 er siste versjon

2021-03-19 15:28 UTC, azaxarov commented on src/main/resources/application.yml
> +    sparqlservice: http://fdk-sparql-service:8080
Jeg ser ikke behov å lage nøsting her:
```suggestion
    datasets-uri: http://fdk-dataset-harvester:8080/catalogs
    data-services-uri: http://fdk-dataservice-harvester:8080/catalogs
    concepts-uri: http://fdk-concept-harvester:8080/concepts
    information-models-uri: http://fdk-informationmodel-harvester:8080/catalogs
    events-uri: http://fdk-event-harvester:8080/events
    organizations-uri: http://organization-catalogue:8080/organizations
    public-services-uri: http://fdk-public-service-harvester:8080/public-services
    sparql-service-uri: http://fdk-sparql-service:8080
```

2021-03-19 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/config/ApplicationURI.kt
> +data class ApplicationURI(
Kan renames til ApplicationProperties

2021-03-19 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/SPARQLAdapter.kt
> +        val sparqlURI = "${uris.sparqlservice}/fuseki/harvested?graph=$graphName"
```suggestion
        val sparqlURI = "${applicationPropertie.sparqlServiceUri}/fuseki/harvested?graph=$graphName"
```

2021-03-19 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
> +                if (it != CatalogType.CONCEPTS) {
Er det mulig å bruke filter her får å bli kvitt denne if-setningen?

2021-03-19 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
>  }
```suggestion
}

```

2021-03-19 15:28 UTC, azaxarov commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
> +class TransformActivity(
Foreslår en rename til TransformationService eller TransformService for å holde navngivning konsekvent med komponent typen

2021-03-22 07:00 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
> +                if (it != CatalogType.CONCEPTS) {
Er ikke liste, så nei. Skal uansett fjernes så snart vi har stablet ny concept-harvester på beina, så du trenger ikke gremmes så veldig lenge av denne :P

2021-03-22 07:00 UTC, NilsOveTen commented on src/main/resources/application.yml
> +    sparqlservice: http://fdk-sparql-service:8080
Planen var vel å ha flere properties-filer, men kom tydeligvis ikke så langt.

2021-03-22 07:00 UTC, NilsOveTen commented on Dockerfile
> +COPY /target/fdk-data-transformation-service.jar app.jar
Hvorfor er det viktig at alle dockerfiler ser like ut?

2021-03-22 07:32 UTC, NilsOveTen commented on Dockerfile
> +COPY /target/fdk-data-transformation-service.jar app.jar
Ser ikke helt vitsen,  men har vel heller ikke spesielt til argument mot å bare endre det. Så why not: 458e32b

2021-03-22 07:33 UTC, NilsOveTen commented on pom.xml
> +        <finalName>${project.artifactId}</finalName>
458e32b

2021-03-22 07:34 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
> +class TransformActivity(
Ikke helt forslaget ditt, men dette var mer korrekt i forhold til hva som skjer i klassene: ddbfbbf

2021-03-22 07:34 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/transform/TransformActivity.kt
>  }
ddbfbbf

2021-03-22 07:34 UTC, NilsOveTen commented on pom.xml
> +        <version>2.4.2</version>
ddbfbbf

2021-03-22 07:35 UTC, NilsOveTen commented on src/main/resources/application.yml
> +    sparqlservice: http://fdk-sparql-service:8080
Nå er det mer behov for nøsting: ddbfbbf

2021-03-22 07:35 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/config/ApplicationURI.kt
> +data class ApplicationURI(
ddbfbbf

2021-03-22 07:35 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_data_transformation_service/adapter/SPARQLAdapter.kt
> +        val sparqlURI = "${uris.sparqlservice}/fuseki/harvested?graph=$graphName"
ddbfbbf

2021-03-22 07:53 UTC, azaxarov commented on Dockerfile
> +COPY /target/fdk-data-transformation-service.jar app.jar
Kun for at det skal være enkelt å kopiere eksisterende dockerfiler og kunne bruke de uten å tenke på innholdet

2021-03-22 07:58 UTC, azaxarov approved these changes

2021-03-22 08:21 UTC, merged